import { NewEraProduct } from './types';

export const INITIAL_NEW_ERA_PRODUCTS: NewEraProduct[] = [
  // ==========================================
  // 1. VISERA CURVA (DAD CAPS CON REGULADOR)
  // ==========================================
  {
    id: 'cap-curva-01',
    sku: 'VC-NY-NVY',
    name: 'Gorra Visera Curva New York Urbana (Con Regulador)',
    brand: 'BRAYSA CAPS',
    silhouette: 'Visera Curva',
    silhouetteCategory: 'Visera Curva',
    team: 'NY Bordado',
    league: 'URBANO',
    price: 70,
    originalPrice: 85,
    promoText: '2 x Bs. 120 (Ahorras Bs. 20)',
    regulatorType: 'Hebilla Metálica',
    sinImpuestos: 70,
    cuotasAmount: 35,
    cuotasText: 'Disponible en tienda física y envíos',
    freeShipping: true,
    isSoldOut: false,
    rating: 5.0,
    reviewCount: 18,
    images: [
      '/cdn/p_yankees_navy.jpg',
      '/cdn/p_yankees_black.jpg',
    ],
    colors: [
      { name: 'Azul Marino', hex: '#1e3a8a' },
      { name: 'Negro Mate', hex: '#111827' },
    ],
    sizes: ['Unitalla Ajustable'],
    description: 'Gorra clásica de 6 paneles con visera curva precurvada. Regulador trasero de correa con hebilla metálica resistente que se adapta a cualquier tamaño de cabeza.',
  },
  {
    id: 'cap-curva-02',
    sku: 'VC-LA-BLK',
    name: 'Gorra Visera Curva Los Angeles Street (Con Regulador)',
    brand: 'BRAYSA CAPS',
    silhouette: 'Visera Curva',
    silhouetteCategory: 'Visera Curva',
    team: 'LA Bordado',
    league: 'URBANO',
    price: 70,
    originalPrice: 85,
    promoText: '2 x Bs. 120 (Ahorras Bs. 20)',
    regulatorType: 'Hebilla Metálica',
    sinImpuestos: 70,
    cuotasAmount: 35,
    cuotasText: 'Disponible en tienda física y envíos',
    freeShipping: true,
    isSoldOut: false,
    rating: 5.0,
    reviewCount: 24,
    images: [
      '/cdn/p_dodgers_black.jpg',
      '/cdn/p_dodgers_blue.jpg',
    ],
    colors: [
      { name: 'Negro Clásico', hex: '#18181b' },
      { name: 'Azul Royal', hex: '#1d4ed8' },
    ],
    sizes: ['Unitalla Ajustable'],
    description: 'Estilo Dad Cap urbano con bordado frontal en alto relieve. Corona suave y cómoda, tela 100% algodón y correa ajustable para ajuste perfecto.',
  },
  {
    id: 'cap-curva-03',
    sku: 'VC-BOS-RED',
    name: 'Gorra Visera Curva Red Sox Clásica (Hebilla Regulable)',
    brand: 'BRAYSA CAPS',
    silhouette: 'Visera Curva',
    silhouetteCategory: 'Visera Curva',
    team: 'Boston Clásico',
    league: 'URBANO',
    price: 70,
    originalPrice: 85,
    promoText: '2 x Bs. 120 (Ahorras Bs. 20)',
    regulatorType: 'Hebilla Metálica',
    sinImpuestos: 70,
    cuotasAmount: 35,
    cuotasText: 'Disponible en tienda física y envíos',
    freeShipping: false,
    isSoldOut: false,
    rating: 4.9,
    reviewCount: 15,
    images: [
      '/cdn/p_yankees_red.jpg',
      '/cdn/p_yankees_1.jpg',
    ],
    colors: [
      { name: 'Rojo Carmesí', hex: '#b91c1c' },
      { name: 'Negro', hex: '#18181b' },
    ],
    sizes: ['Unitalla Ajustable'],
    description: 'Modelo clásico de visera curva con broche de metal graduable. Acabado transpirable con ojales bordados, ideal para uso diario.',
  },

  // ==========================================
  // 2. VISERA PLANA (SNAPBACKS CON REGULADOR)
  // ==========================================
  {
    id: 'cap-plana-01',
    sku: 'VP-SNAP-TEX',
    name: 'Gorra Visera Plana Texas Ranger Snapback (Broche Ajustable)',
    brand: 'BRAYSA CAPS',
    silhouette: 'Visera Plana',
    silhouetteCategory: 'Visera Plana',
    team: 'Texas Rangers',
    league: 'STREETWEAR',
    price: 80,
    originalPrice: 95,
    promoText: '2 x Bs. 140 (Ahorras Bs. 20)',
    regulatorType: 'Broche Snapback',
    sinImpuestos: 80,
    cuotasAmount: 40,
    cuotasText: 'Disponible para entrega inmediata',
    freeShipping: true,
    isSoldOut: false,
    rating: 5.0,
    reviewCount: 31,
    images: [
      '/cdn/p_rangers_1.jpg',
      '/cdn/p_rangers_2.jpg',
    ],
    colors: [
      { name: 'Negro Pinstripe', hex: '#111827' },
      { name: 'Azul Marino', hex: '#1e3a8a' },
    ],
    sizes: ['Unitalla Ajustable'],
    description: 'Corona alta estructurada con visera plana rígida. Sistema de broche a presión (Snapback clásico de 7 puntos) para regular fácilmente a cualquier medida.',
  },
  {
    id: 'cap-plana-02',
    sku: 'VP-SNAP-SOX',
    name: 'Gorra Visera Plana White Sox Edición Especial (Broche Regulable)',
    brand: 'BRAYSA CAPS',
    silhouette: 'Visera Plana',
    silhouetteCategory: 'Visera Plana',
    team: 'Chicago White Sox',
    league: 'STREETWEAR',
    price: 80,
    originalPrice: 95,
    promoText: '2 x Bs. 140 (Ahorras Bs. 20)',
    regulatorType: 'Broche Snapback',
    sinImpuestos: 80,
    cuotasAmount: 40,
    cuotasText: 'Disponible para entrega inmediata',
    freeShipping: true,
    isSoldOut: false,
    rating: 5.0,
    reviewCount: 22,
    images: [
      '/cdn/p_sox_bloom_1.jpg',
      '/cdn/p_sox_bloom_2.jpg',
    ],
    colors: [
      { name: 'Beige Arena', hex: '#e7e5e4' },
      { name: 'Negro Tonal', hex: '#18181b' },
    ],
    sizes: ['Unitalla Ajustable'],
    description: 'Diseño urbano moderno con bordado en relieve. Visera plana con reverso verde vintage y broche de plástico regulador en la parte trasera.',
  },
  {
    id: 'cap-plana-03',
    sku: 'VP-SNAP-OAK',
    name: 'Gorra Visera Plana Oakland Athletics Snapback Bicolor',
    brand: 'BRAYSA CAPS',
    silhouette: 'Visera Plana',
    silhouetteCategory: 'Visera Plana',
    team: 'Oakland A’s',
    league: 'STREETWEAR',
    price: 80,
    originalPrice: 95,
    promoText: '2 x Bs. 140 (Ahorras Bs. 20)',
    regulatorType: 'Broche Snapback',
    sinImpuestos: 80,
    cuotasAmount: 40,
    cuotasText: 'Disponible para entrega inmediata',
    freeShipping: true,
    isSoldOut: false,
    rating: 4.8,
    reviewCount: 19,
    images: [
      '/cdn/p_athletics_1.jpg',
      '/cdn/p_athletics_2.jpg',
    ],
    colors: [
      { name: 'Verde / Amarillo', hex: '#166534' },
      { name: 'Negro Puro', hex: '#111111' },
    ],
    sizes: ['Unitalla Ajustable'],
    description: 'Combinación icónica bicolor con visera plana resistente y regulador snapback trasero multiposición.',
  },

  // ==========================================
  // 3. TRUCKER (GORRAS CON MALLA TRANSPIRABLE)
  // ==========================================
  {
    id: 'cap-trucker-01',
    sku: 'TRK-DODG-BLU',
    name: 'Gorra Trucker Dodgers con Malla de Ventilación (Broche Regulable)',
    brand: 'BRAYSA CAPS',
    silhouette: 'Trucker',
    silhouetteCategory: 'Trucker',
    team: 'LA Dodgers Trucker',
    league: 'URBANO',
    price: 65,
    originalPrice: 80,
    promoText: '2 x Bs. 110 (Ahorras Bs. 20)',
    regulatorType: 'Broche Snapback',
    sinImpuestos: 65,
    cuotasAmount: 32,
    cuotasText: 'Disponible en tienda y envíos',
    freeShipping: true,
    isSoldOut: false,
    rating: 5.0,
    reviewCount: 42,
    images: [
      '/cdn/p_3930_dodgers.jpg',
      '/cdn/p_recycled_dodgers.jpg',
    ],
    colors: [
      { name: 'Azul con Malla Blanca', hex: '#1e40af' },
      { name: 'Negro Completo', hex: '#0f172a' },
    ],
    sizes: ['Unitalla Ajustable'],
    description: 'Frontal acolchado estructurado con paneles traseros de malla que permiten ventilación total. Broche snapback trasero ajustable para máxima comodidad.',
  },
  {
    id: 'cap-trucker-02',
    sku: 'TRK-YANK-BLK',
    name: 'Gorra Trucker Yankees Blackout (Con Malla y Regulador)',
    brand: 'BRAYSA CAPS',
    silhouette: 'Trucker',
    silhouetteCategory: 'Trucker',
    team: 'NY Yankees Trucker',
    league: 'URBANO',
    price: 65,
    originalPrice: 80,
    promoText: '2 x Bs. 110 (Ahorras Bs. 20)',
    regulatorType: 'Broche Snapback',
    sinImpuestos: 65,
    cuotasAmount: 32,
    cuotasText: 'Disponible en tienda y envíos',
    freeShipping: true,
    isSoldOut: false,
    rating: 4.9,
    reviewCount: 27,
    images: [
      '/cdn/p_3930_yankees.jpg',
      '/cdn/p_recycled_yankees.jpg',
    ],
    colors: [
      { name: 'Negro All-Black', hex: '#111827' },
      { name: 'Gris Grafito', hex: '#4b5563' },
    ],
    sizes: ['Unitalla Ajustable'],
    description: 'Estilo trucker moderno all-black. Fresca, ligera y adaptable para climas cálidos con broche a presión graduable.',
  },

  // ==========================================
  // 4. LISAS / BÁSICAS (MINIMALISTAS SIN LOGO)
  // ==========================================
  {
    id: 'cap-lisa-01',
    sku: 'BAS-LISA-BLK',
    name: 'Gorra Básica Lisa Visera Curva (10 Colores en Stock)',
    brand: 'BRAYSA CAPS',
    silhouette: 'Básica Lisa',
    silhouetteCategory: 'Básica Lisa',
    team: 'Básica Monocromática',
    league: 'BÁSICOS',
    price: 60,
    originalPrice: 75,
    promoText: '2 x Bs. 100 (Ahorras Bs. 20)',
    regulatorType: 'Hebilla Metálica',
    sinImpuestos: 60,
    cuotasAmount: 30,
    cuotasText: 'Ideal para uso diario o bordado',
    freeShipping: true,
    isSoldOut: false,
    rating: 5.0,
    reviewCount: 35,
    images: [
      '/cdn/tinted/cap_negro.jpg',
      '/cdn/tinted/cap_blanco.jpg',
      '/cdn/tinted/cap_azul_marino.jpg',
      '/cdn/tinted/cap_rojo.jpg',
      '/cdn/tinted/cap_verde_militar.jpg',
      '/cdn/tinted/cap_beige.jpg',
      '/cdn/tinted/cap_vino.jpg',
      '/cdn/tinted/cap_mostaza.jpg',
      '/cdn/tinted/cap_gris.jpg',
      '/cdn/tinted/cap_cafe.jpg',
    ],
    colors: [
      { name: 'Negro Clásico', hex: '#18181b', image: '/cdn/tinted/cap_negro.jpg' },
      { name: 'Blanco Puro', hex: '#f8fafc', image: '/cdn/tinted/cap_blanco.jpg' },
      { name: 'Azul Marino', hex: '#1e3a8a', image: '/cdn/tinted/cap_azul_marino.jpg' },
      { name: 'Rojo Carmesí', hex: '#dc2626', image: '/cdn/tinted/cap_rojo.jpg' },
      { name: 'Verde Militar', hex: '#4d5d36', image: '/cdn/tinted/cap_verde_militar.jpg' },
      { name: 'Beige Khaki', hex: '#c5b396', image: '/cdn/tinted/cap_beige.jpg' },
      { name: 'Vino Tinto', hex: '#651c28', image: '/cdn/tinted/cap_vino.jpg' },
      { name: 'Mostaza', hex: '#d97706', image: '/cdn/tinted/cap_mostaza.jpg' },
      { name: 'Gris Jaspe', hex: '#4b5563', image: '/cdn/tinted/cap_gris.jpg' },
      { name: 'Café Tabaco', hex: '#573926', image: '/cdn/tinted/cap_cafe.jpg' },
    ],
    sizes: ['Unitalla Ajustable'],
    description: 'Gorra lisa clásica de 6 paneles en gabardina de algodón premium. Regulador de correa con pasador metálico graduable. Disponible en los 10 colores en tendencia para combinar con cualquier outfit.',
  },
  {
    id: 'cap-lisa-02',
    sku: 'BAS-SNAP-BLK',
    name: 'Gorra Básica Visera Plana Lisa Snapback (Broche Regulable)',
    brand: 'BRAYSA CAPS',
    silhouette: 'Básica Lisa',
    silhouetteCategory: 'Básica Lisa',
    team: 'Streetwear Básico',
    league: 'BÁSICOS',
    price: 65,
    originalPrice: 80,
    promoText: '2 x Bs. 110 (Ahorras Bs. 20)',
    regulatorType: 'Broche Snapback',
    sinImpuestos: 65,
    cuotasAmount: 32,
    cuotasText: 'Lista para usar o bordar',
    freeShipping: true,
    isSoldOut: false,
    rating: 4.8,
    reviewCount: 14,
    images: [
      '/cdn/p_food_icon.jpg',
      '/cdn/p_bad_bunny.jpg',
    ],
    colors: [
      { name: 'Negro Puro', hex: '#000000' },
      { name: 'Rojo Pasión', hex: '#dc2626' },
      { name: 'Azul Marino', hex: '#172554' },
    ],
    sizes: ['Unitalla Ajustable'],
    description: 'Silueta plana de 6 paneles estructurada sin logos frontales. Broche a presión ajustable para cualquier circunferencia de cabeza.',
  },
];

export const POPULAR_PRODUCTS: NewEraProduct[] = INITIAL_NEW_ERA_PRODUCTS.slice(0, 6);

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  date: string;
  image: string;
  excerpt: string;
}

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'post-1',
    slug: 'guia-ajuste-reguladores',
    title: 'Cómo graduar tu gorra con broche y hebilla metálica al tamaño exacto',
    date: '04 Oct 2026',
    image: '/cdn/p_yankees_1.jpg',
    excerpt: 'Aprende los mejores consejos para mantener la forma y el calce perfecto de tu gorra streetwear.',
  },
  {
    id: 'post-2',
    slug: 'cuidado-gorras-streetwear',
    title: 'Secretos para lavar y cuidar la visera de tus gorras sin deformarlas',
    date: '01 Oct 2026',
    image: '/cdn/p_dodgers_black.jpg',
    excerpt: 'Mantén los colores vivos y las viseras intactas con esta guía paso a paso para amantes del headwear.',
  },
  {
    id: 'post-3',
    slug: 'tendencias-gorras-bolivia',
    title: 'Las siluetas y combinaciones de visera curva más buscadas este año',
    date: '28 Sep 2026',
    image: '/cdn/p_rangers_1.jpg',
    excerpt: 'Descubre los colores y acabados en tendencia en el streetwear boliviano para esta temporada.',
  },
];
